### ISSUE TITLE
How to install this program / library?

### ISSUE THREAD

**Issue by irlabs** [manuelbua/blur-ninja#5]
Hi,

I tried to install it with `pip install blur-ninja`, but it cannot find a distribution.

Was a distribution packages uploaded to the Python Package Index?

**Comment by manuelbua** [comment]
Sorry but currently there is no way to install it via `pip`: i'm struggling to find some time to work it out, but in the meantime you may clone the repo and use it from there.

**Comment by irlabs** [comment]
Can't get it to work.
After `pip install -r requirements.txt` and `python setup.py install` it tells me

```
Traceback (most recent call last):
  File "/usr/local/bin/blurninja", line 11, in <module>
    load_entry_point('blur-ninja==1.0.0', 'console_scripts', 'blurninja')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named blurninja.app
```
